### ISSUE TITLE
Delay between frames for a webp is off after upload.

### ISSUE THREAD

**Issue by Matthew-Grayson** [SevenTV/image-processor#85]
An uploaded webp has delay times between frames that are significantly longer than specified in the original file. The original file has delays set individually for each frame ranging from 17ms to 450ms. The shorter delays seem to have been lengthened.

[Here is a webp before upload.](https://cdn.discordapp.com/attachments/434160153806372874/1050598799380316220/MiyamotoArriveW.webp)

[And here is a link to the resulting emote on 7tv.](https://7tv.app/emotes/63929100c542c13da391b48f)

**Comment by Excellify** [comment]
Im assuming this is a result of the way gif timings are rendered in browsers where any delay below 20ms(?) gets rounded up. The processor does some stuff to work with this limitation, which might be causing you issues.

**Comment by brian6932** [comment]
_To circumvent GitHub image processing, all files are href-ed to their original versions, there is no way to bypass GitHub image cache unfortunately_

Can confirm, 7TV breaks frametimes that exceed the gif spec (50 fps (20ms frametime)), instead of breaking the frametimes, it should really just not create a gif version of the emote.

In my case, this animation has fps too high to be a gif

<details>
	<summary>source file</summary>
	<a href="https://i.alienpls.org/PADORU.apng">
		<img src="https://i.alienpls.org/PADORU.apng">
	</a>
</details>

<details>
	<summary>webp encoded</summary>
	<a href="https://cdn.7tv.app/emote/639ac02337089454894ed835/4x.webp">
		<img src="https://cdn.7tv.app/emote/639ac02337089454894ed835/4x.webp">
	</a>
</details>

<details>
	<summary>avif encoded</summary>
	<a href="https://cdn.7tv.app/emote/639ac02337089454894ed835/4x.avif">
		<img src="https://cdn.7tv.app/emote/639ac02337089454894ed835/4x.avif">
	</a>
</details>

<details>
	<summary>gif encoded</summary>
	<a href="https://cdn.7tv.app/emote/639ac02337089454894ed835/4x.gif">
		<img src="https://cdn.7tv.app/emote/639ac02337089454894ed835/4x.gif">
	</a>
</details>

**Comment by Matthew-Grayson** [comment]
Thank you for the response. I was actually able to fix the issue by changing the 17ms delays to 20ms.Sent from my iPhoneOn Dec 9, 2022, at 4:46 AM, Excellify ***@***.***> wrote:﻿
Im assuming this is a result of the way gif timings are rendered in browsers where any delay below 20ms(?) gets rounded up. The processor does some stuff to work with this limitation, which might be causing you issues.
